version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - app-network

  web:
    build: .
    expose:
      - "8001"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  celery_worker:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: celery -A app.worker worker --loglevel=info
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  redis:
    image: redis:7.0
    expose:
      - "6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 